name: word_game
description: Flutter words game
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  drift: ^2.28.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
